// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (
        id,
        token_hash,
        expires_at,
        revoked_at,
        user_id,
        device_info_id
    )
VALUES (
        ?1,
        ?2,
        ?3,
        NULL,
        ?4,
        ?5
    )
`

type CreateRefreshTokenParams struct {
	ID           string
	TokenHash    string
	ExpiresAt    sql.NullTime
	UserID       string
	DeviceInfoID string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserID,
		arg.DeviceInfoID,
	)
	return err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens
SET revoked_at = ?1
WHERE user_id = ?2
    AND device_info_id = ?3
    AND revoked_at IS NULL
`

type RevokeTokenParams struct {
	RevokedAt    sql.NullTime
	UserID       string
	DeviceInfoID string
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeToken, arg.RevokedAt, arg.UserID, arg.DeviceInfoID)
	return err
}
