// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (
        id,
        token_hash,
        expires_at,
        revoked_at,
        user_id,
        device_info_id
    )
VALUES (
        gen_random_uuid(),
        ?1,
        DATETIME('now', '+60 days'),
        NULL,
        ?2,
        ?3
    )
`

type CreateRefreshTokenParams struct {
	TokenHash    sql.NullString
	UserID       interface{}
	DeviceInfoID interface{}
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.TokenHash, arg.UserID, arg.DeviceInfoID)
	return err
}
