// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/seanhuebl/unity-wealth/internal/models"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (
        id,
        token_hash,
        expires_at,
        revoked_at,
        user_id,
        device_info_id
    )
VALUES (
        $1,
        $2,
        $3,
        NULL,
        $4,
        $5
    )
` // #nosec

type CreateRefreshTokenParams struct {
	ID           uuid.UUID
	TokenHash    string
	ExpiresAt    sql.NullTime
	UserID       uuid.UUID
	DeviceInfoID uuid.UUID
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserID,
		arg.DeviceInfoID,
	)
	return err
}

const getRefreshByUserAndDevice = `-- name: GetRefreshByUserAndDevice :one
SELECT id, device_info_id, user_id, token_hash, created_at, updated_at, expires_at, revoked_at
FROM refresh_tokens
WHERE user_id = $1
    AND device_info_id = $2
`

type GetRefreshByUserAndDeviceParams struct {
	UserID       uuid.UUID
	DeviceInfoID uuid.UUID
}

func (q *Queries) GetRefreshByUserAndDevice(ctx context.Context, arg GetRefreshByUserAndDeviceParams) (models.RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshByUserAndDevice, arg.UserID, arg.DeviceInfoID)
	var i models.RefreshToken
	err := row.Scan(
		&i.ID,
		&i.DeviceInfoID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens
SET revoked_at = $1
WHERE user_id = $2
    AND device_info_id = $3
    AND revoked_at IS NULL
` // #nosec

type RevokeTokenParams struct {
	RevokedAt    sql.NullTime
	UserID       uuid.UUID
	DeviceInfoID uuid.UUID
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeToken, arg.RevokedAt, arg.UserID, arg.DeviceInfoID)
	return err
}
