// Code generated by mockery v2.53.4. DO NOT EDIT.

package dbmocks

import (
	context "context"

	database "github.com/seanhuebl/unity-wealth/internal/database"
	mock "github.com/stretchr/testify/mock"

	models "github.com/seanhuebl/unity-wealth/internal/models"

	uuid "github.com/google/uuid"
)

// TransactionQuerier is an autogenerated mock type for the TransactionQuerier type
type TransactionQuerier struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: ctx, arg
func (_m *TransactionQuerier) CreateTransaction(ctx context.Context, arg database.CreateTransactionParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateTransactionParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTransactionByID provides a mock function with given fields: ctx, arg
func (_m *TransactionQuerier) DeleteTransactionByID(ctx context.Context, arg database.DeleteTransactionByIDParams) (uuid.UUID, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransactionByID")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.DeleteTransactionByIDParams) (uuid.UUID, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.DeleteTransactionByIDParams) uuid.UUID); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.DeleteTransactionByIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailedCategories provides a mock function with given fields: ctx
func (_m *TransactionQuerier) GetDetailedCategories(ctx context.Context) ([]models.DetailedCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailedCategories")
	}

	var r0 []models.DetailedCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.DetailedCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.DetailedCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DetailedCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailedCategoryID provides a mock function with given fields: ctx, name
func (_m *TransactionQuerier) GetDetailedCategoryID(ctx context.Context, name string) (int32, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailedCategoryID")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int32, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int32); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPrimaryCategories provides a mock function with given fields: ctx
func (_m *TransactionQuerier) GetPrimaryCategories(ctx context.Context) ([]models.PrimaryCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPrimaryCategories")
	}

	var r0 []models.PrimaryCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.PrimaryCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.PrimaryCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PrimaryCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserTransactionByID provides a mock function with given fields: ctx, arg
func (_m *TransactionQuerier) GetUserTransactionByID(ctx context.Context, arg database.GetUserTransactionByIDParams) (database.GetUserTransactionByIDRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTransactionByID")
	}

	var r0 database.GetUserTransactionByIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetUserTransactionByIDParams) (database.GetUserTransactionByIDRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetUserTransactionByIDParams) database.GetUserTransactionByIDRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.GetUserTransactionByIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetUserTransactionByIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserTransactionsFirstPage provides a mock function with given fields: ctx, arg
func (_m *TransactionQuerier) GetUserTransactionsFirstPage(ctx context.Context, arg database.GetUserTransactionsFirstPageParams) ([]database.GetUserTransactionsFirstPageRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTransactionsFirstPage")
	}

	var r0 []database.GetUserTransactionsFirstPageRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetUserTransactionsFirstPageParams) ([]database.GetUserTransactionsFirstPageRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetUserTransactionsFirstPageParams) []database.GetUserTransactionsFirstPageRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetUserTransactionsFirstPageRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetUserTransactionsFirstPageParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserTransactionsPaginated provides a mock function with given fields: ctx, arg
func (_m *TransactionQuerier) GetUserTransactionsPaginated(ctx context.Context, arg database.GetUserTransactionsPaginatedParams) ([]database.GetUserTransactionsPaginatedRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTransactionsPaginated")
	}

	var r0 []database.GetUserTransactionsPaginatedRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetUserTransactionsPaginatedParams) ([]database.GetUserTransactionsPaginatedRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetUserTransactionsPaginatedParams) []database.GetUserTransactionsPaginatedRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetUserTransactionsPaginatedRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetUserTransactionsPaginatedParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTransactionByID provides a mock function with given fields: ctx, arg
func (_m *TransactionQuerier) UpdateTransactionByID(ctx context.Context, arg database.UpdateTransactionByIDParams) (database.UpdateTransactionByIDRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionByID")
	}

	var r0 database.UpdateTransactionByIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateTransactionByIDParams) (database.UpdateTransactionByIDRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateTransactionByIDParams) database.UpdateTransactionByIDRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.UpdateTransactionByIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.UpdateTransactionByIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionQuerier creates a new instance of TransactionQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionQuerier {
	mock := &TransactionQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
