// Code generated by mockery v2.53.4. DO NOT EDIT.

package handlermocks

import (
	context "context"

	models "github.com/seanhuebl/unity-wealth/internal/models"
	mock "github.com/stretchr/testify/mock"

	servicestransaction "github.com/seanhuebl/unity-wealth/internal/services/transaction"

	uuid "github.com/google/uuid"
)

// TransactionService is an autogenerated mock type for the TransactionService type
type TransactionService struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: ctx, userID, req
func (_m *TransactionService) CreateTransaction(ctx context.Context, userID uuid.UUID, req models.NewTxRequest) (*models.Tx, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 *models.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.NewTxRequest) (*models.Tx, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.NewTxRequest) *models.Tx); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.NewTxRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTransaction provides a mock function with given fields: ctx, txnID, userID
func (_m *TransactionService) DeleteTransaction(ctx context.Context, txnID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, txnID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, txnID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTransactionByID provides a mock function with given fields: ctx, userID, txnID
func (_m *TransactionService) GetTransactionByID(ctx context.Context, userID uuid.UUID, txnID uuid.UUID) (*models.Tx, error) {
	ret := _m.Called(ctx, userID, txnID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByID")
	}

	var r0 *models.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Tx, error)); ok {
		return rf(ctx, userID, txnID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Tx); ok {
		r0 = rf(ctx, userID, txnID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, txnID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUserTransactions provides a mock function with given fields: ctx, userID, cursorToken, pageSize
func (_m *TransactionService) ListUserTransactions(ctx context.Context, userID uuid.UUID, cursorToken string, pageSize int32) (servicestransaction.ListTxResult, error) {
	ret := _m.Called(ctx, userID, cursorToken, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListUserTransactions")
	}

	var r0 servicestransaction.ListTxResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32) (servicestransaction.ListTxResult, error)); ok {
		return rf(ctx, userID, cursorToken, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32) servicestransaction.ListTxResult); ok {
		r0 = rf(ctx, userID, cursorToken, pageSize)
	} else {
		r0 = ret.Get(0).(servicestransaction.ListTxResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int32) error); ok {
		r1 = rf(ctx, userID, cursorToken, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTransaction provides a mock function with given fields: ctx, txnID, userID, req
func (_m *TransactionService) UpdateTransaction(ctx context.Context, txnID uuid.UUID, userID uuid.UUID, req models.NewTxRequest) (*models.Tx, error) {
	ret := _m.Called(ctx, txnID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransaction")
	}

	var r0 *models.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.NewTxRequest) (*models.Tx, error)); ok {
		return rf(ctx, txnID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.NewTxRequest) *models.Tx); ok {
		r0 = rf(ctx, txnID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, models.NewTxRequest) error); ok {
		r1 = rf(ctx, txnID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionService creates a new instance of TransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionService {
	mock := &TransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
