@CODESPACE_BASE_URL=https://supreme-space-broccoli-pqrqww44q4qfrwr9-8080.app.github.dev
@LOCAL_BASE_URL=http://localhost:8080


POST {{CODESPACE_BASE_URL}}/api/signup 
Content-Type: application/json

{
    "email": "sean@example.com",
    "password": "SecurePass123!"
}

###

POST {{CODESPACE_BASE_URL}}/api/login
Content-Type: application/json
X-Device-Info: os=iOS; os_version=14.4; device_type=Mobile; browser=Safari; browser_version=14.0

{
    "email": "sean@example.com",
    "password": "SecurePass123!"
}