// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testmodels "github.com/seanhuebl/unity-wealth/internal/testmodels"
)

// BaseAccess is an autogenerated mock type for the BaseAccess type
type BaseAccess struct {
	mock.Mock
}

// BaseAccess provides a mock function with no fields
func (_m *BaseAccess) BaseAccess() testmodels.BaseHTTPTestCase {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BaseAccess")
	}

	var r0 testmodels.BaseHTTPTestCase
	if rf, ok := ret.Get(0).(func() testmodels.BaseHTTPTestCase); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(testmodels.BaseHTTPTestCase)
	}

	return r0
}

// NewBaseAccess creates a new instance of BaseAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBaseAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *BaseAccess {
	mock := &BaseAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
