// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// TxPageRow is an autogenerated mock type for the TxPageRow type
type TxPageRow struct {
	mock.Mock
}

// GetAmountCents provides a mock function with no fields
func (_m *TxPageRow) GetAmountCents() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAmountCents")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetDetailedCatID provides a mock function with no fields
func (_m *TxPageRow) GetDetailedCatID() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDetailedCatID")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetMerchant provides a mock function with no fields
func (_m *TxPageRow) GetMerchant() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMerchant")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTxDate provides a mock function with no fields
func (_m *TxPageRow) GetTxDate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTxDate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTxID provides a mock function with no fields
func (_m *TxPageRow) GetTxID() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTxID")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// GetUserID provides a mock function with no fields
func (_m *TxPageRow) GetUserID() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// NewTxPageRow creates a new instance of TxPageRow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxPageRow(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxPageRow {
	mock := &TxPageRow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
