// Code generated by mockery v2.51.1. DO NOT EDIT.

package handlermocks

import (
	context "context"

	models "github.com/seanhuebl/unity-wealth/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, input
func (_m *AuthService) Login(ctx context.Context, input models.LoginInput) (models.LoginResponse, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 models.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.LoginInput) (models.LoginResponse, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.LoginInput) models.LoginResponse); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.LoginInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
