// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type DetailedCategory struct {
	ID                int32
	Name              string
	Description       string
	PrimaryCategoryID int32
}

type DeviceInfoLog struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	DeviceType     string
	Browser        string
	BrowserVersion string
	Os             string
	OsVersion      string
	AppInfo        pqtype.NullRawMessage
	CreatedAt      time.Time
	LastUsedAt     time.Time
}

type PrimaryCategory struct {
	ID   int32
	Name string
}

type RefreshToken struct {
	ID           uuid.UUID
	DeviceInfoID uuid.UUID
	UserID       uuid.UUID
	TokenHash    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ExpiresAt    sql.NullTime
	RevokedAt    sql.NullTime
}

type Transaction struct {
	ID                 uuid.UUID
	DetailedCategoryID int32
	UserID             uuid.UUID
	TransactionDate    time.Time
	Merchant           string
	AmountCents        int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type User struct {
	ID                   uuid.UUID
	Email                string
	HashedPassword       string
	RiskPreference       interface{}
	PlanType             interface{}
	StripeCustomerID     sql.NullString
	StripeSubscriptionID sql.NullString
	ScholarshipFlag      bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
